name: orders-pipeline

on:
  push:
    branches:
      - main
      - feature/*
  pull_request:
    branches:
      - main
      - feature/*
jobs:
  build-and-test:
    name: Build and Test
    uses: Proyecto-Devops-2024/devops-repo/.github/workflows/maven-build-and-test.yml@main

  sonarqube-scan:
    needs: build-and-test
    uses: Proyecto-Devops-2024/devops-repo/.github/workflows/sonarqube-scan-java.yml@main
    with:
      sonar_project_key: Proyecto-Devops-2024_orders-service

  deploy-dev:
    needs: sonarqube-scan
    runs-on: ubuntu-latest
    steps:
      - name: Deploy
        run: echo "Deploying to ECS dev..."

  deploy-staging:
    needs: deploy-dev
    runs-on: ubuntu-latest
    steps:
      - name: Deploy
        run: echo "Deploying to ECS staging..."

  manual-aprove:
    needs: deploy-staging
    runs-on: ubuntu-latest
    steps:
      - name: Approve
        run: echo "Approving..."

  deploy-prod:
    needs: manual-aprove
    runs-on: ubuntu-latest
    steps:
      - name: Deploy
        run: echo "Deploying to ECS prod..."

