name: orders-pipeline

on:
  push:
    branches:
      - main
      - feature/*
  pull_request:
    branches:
      - main
      - feature/*
  workflow_dispatch:

permissions: write-all

jobs:
  main-workflow:
    uses: Proyecto-Devops-2024/devops-repo/.github/workflows/main.yml@secure-branch
    secrets: inherit
